# Generated by Django 4.1.7 on 2023-02-16 06:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=10, verbose_name='first name')),
                ('last_name', models.CharField(max_length=10, verbose_name='last name')),
                ('subs_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Subscription date')),
                ('tournament_score', models.PositiveSmallIntegerField(default=0, verbose_name='tournament score')),
            ],
            options={
                'ordering': ['tournament_score', 'username'],
            },
        ),
    ]
