# Generated by Django 4.1.7 on 2023-02-16 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='after', max_length=8)),
                ('length_of_tournament', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('launch_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['launch_date'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=1)),
                ('play_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('participants', models.ManyToManyField(to='game.member')),
            ],
        ),
    ]
