# Generated by Django 4.1.7 on 2023-02-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_tournament_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='lIJjNcjN', max_length=8),
        ),
    ]
