# Generated by Django 4.1.7 on 2023-02-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_match_options_match_tournament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='weekday',
            field=models.CharField(default='Monday', max_length=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='BlwcrwQz', max_length=8),
        ),
    ]
