# Generated by Django 4.1.7 on 2023-02-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_match_weekday_alter_tournament_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoreboard',
            old_name='match_id',
            new_name='match',
        ),
        migrations.RenameField(
            model_name='scoreboard',
            old_name='player',
            new_name='member',
        ),
        migrations.RemoveField(
            model_name='match',
            name='participants',
        ),
        migrations.AddField(
            model_name='match',
            name='participants',
            field=models.ManyToManyField(through='game.Scoreboard', to='game.member'),
        ),
        migrations.AlterField(
            model_name='match',
            name='weekday',
            field=models.CharField(default='Friday', max_length=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='yQxMzDxt', max_length=8),
        ),
    ]
