# Generated by Django 4.1.7 on 2023-02-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_rename_match_id_scoreboard_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='sCdCTqLm', max_length=8),
        ),
    ]
