# Generated by Django 4.1.7 on 2023-02-25 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_tournament_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='group',
            field=models.CharField(max_length=1, verbose_name='Match Group'),
        ),
        migrations.AlterField(
            model_name='match',
            name='play_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Match date'),
        ),
        migrations.AlterField(
            model_name='match',
            name='week',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Match week'),
        ),
        migrations.AlterField(
            model_name='match',
            name='weekday',
            field=models.CharField(default='Saturday', max_length=10, verbose_name='Match day'),
        ),
        migrations.AlterField(
            model_name='member',
            name='tournament_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='tournament score'),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=10, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=1, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='ended',
            field=models.BooleanField(default=False, verbose_name='Tournament ended'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='launch_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tournament launch Date'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='length_of_tournament',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Length of Tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='ISyFHlBD', max_length=24, verbose_name='Tournament name'),
        ),
    ]
