# Generated by Django 4.1.7 on 2023-02-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_match_group_alter_match_play_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='EXnhOwzR', max_length=24, verbose_name='Tournament name'),
        ),
    ]
