# Generated by Django 4.1.7 on 2023-03-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_match_options_alter_match_weekday_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['play_date', 'group']},
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='WfRClKLa', max_length=24, verbose_name='Tournament name'),
        ),
    ]
