# Generated by Django 4.1.7 on 2023-03-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_alter_match_options_alter_tournament_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoreboard',
            options={'ordering': ['match__play_date', 'score']},
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='VhVBPWnK', max_length=24, verbose_name='Tournament name'),
        ),
    ]
