# Generated by Django 4.1.7 on 2023-03-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_alter_scoreboard_options_alter_tournament_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='weekday',
            field=models.CharField(default='Sunday', max_length=10, verbose_name='Match day'),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='vgQHtdfQ', max_length=24, verbose_name='Tournament name'),
        ),
    ]
