# Generated by Django 4.1.7 on 2023-03-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_alter_match_weekday_alter_scoreboard_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tournament_score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='tournament score'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='zWEoyrWv', max_length=24, verbose_name='Tournament name'),
        ),
    ]
