# Generated by Django 4.1.7 on 2023-03-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_alter_member_tournament_score_alter_tournament_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='weekday',
            field=models.CharField(default='Monday', max_length=10, verbose_name='Match day'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='ZycBondj', max_length=24, verbose_name='Tournament name'),
        ),
    ]
