# Generated by Django 4.1.7 on 2023-03-11 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_tournament_member_tournament_tournament_final_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='weekday',
            field=models.CharField(default='Saturday', max_length=10, verbose_name='Match day'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='vMLHsMIN', max_length=24, verbose_name='Tournament name'),
        ),
        migrations.CreateModel(
            name='TournamentScoreboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_score', models.PositiveSmallIntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.member')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.tournament')),
            ],
        ),
    ]
