# Generated by Django 4.1.7 on 2023-03-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_alter_match_weekday_alter_tournament_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='weekday',
            field=models.CharField(default='Sunday', max_length=10, verbose_name='Match day'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='oPQjQxwB', max_length=24, verbose_name='Tournament name'),
        ),
    ]
