# Generated by Django 4.1.7 on 2023-03-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_alter_match_weekday_alter_tournament_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='weekday',
            field=models.CharField(default='Monday', max_length=10, verbose_name='Match day'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='pZyfGNjj', max_length=24, verbose_name='Tournament name'),
        ),
    ]
