# Generated by Django 4.1.7 on 2023-03-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_alter_member_options_remove_member_tournament_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterModelOptions(
            name='tournamentscoreboard',
            options={'ordering': ['-tournament_score']},
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='member',
            new_name='members',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='INslEyHB', max_length=24, verbose_name='Tournament name'),
        ),
    ]
