# Generated by Django 4.1.7 on 2023-03-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_rename_members_tournament_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='RiMpJbFn', max_length=24, verbose_name='Tournament name'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(default=['tancali', 'bhrbursa', 'kzlrmk', 'bulenh', 'eminc', 'fhtpgl', 'ihtnd', 'hcangul', 'ha135', 'haozd', 'bbxy', 'husdonmez', '1mckn', 'mcineli', 'mzsah', 'ogeg', 'pazer', '0cean555', 'kasaman5', 'semsov', 'erbilgin', 'yasarustad', 'ylmzs'], to='game.member'),
        ),
    ]
