# Generated by Django 4.1.7 on 2023-03-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_alter_tournament_name_alter_tournament_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='fjybQMim', max_length=24, verbose_name='Tournament name'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(to='game.member'),
        ),
    ]
