# Generated by Django 4.1.7 on 2023-03-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0034_remove_tournament_tournament_final_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='KWjgSsOz', max_length=24, verbose_name='Tournament name'),
        ),
    ]
