# Generated by Django 4.1.7 on 2023-03-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_alter_tournament_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='SfgbPOET', max_length=24, verbose_name='Tournament name'),
        ),
    ]
