# Generated by Django 4.1.7 on 2023-03-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0042_alter_match_weekday_alter_tournament_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentscoreboard',
            options={'ordering': ['tournament', '-tournament_score']},
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='FzqAHSDa', max_length=24, verbose_name='Tournament name'),
        ),
    ]
