# Generated by Django 4.1.7 on 2023-03-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0043_alter_tournamentscoreboard_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-total_points', 'first_name']},
        ),
        migrations.AddField(
            model_name='member',
            name='total_points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='weekday',
            field=models.CharField(default='Thursday', max_length=10, verbose_name='Match day'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='msFipCfk', max_length=24, verbose_name='Tournament name'),
        ),
    ]
